services:
  job-tracker-backend:
    build: ./backend
    container_name: job-tracker-backend
    volumes:
      - ./backend:/app
    env_file: "./backend/.env"
    environment:
      - IS_DOCKER_CONTAINER=1
    networks:
      - proxy
      - internal
    depends_on:
      db:
        condition: service_healthy
    restart: always

  job-tracker-frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://job.prakharmodi.me/backend
        NEXT_PUBLIC_APP_URL: https://job.prakharmodi.me
    container_name: job-tracker-frontend
    env_file: "./frontend/.env"
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    restart: always

  db:
    image: postgres:13
    container_name: job-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobseeker_analytics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobseeker_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  proxy:
    external: true
  internal:
    driver: bridge

volumes:
  postgres_data:
